DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Commitee;
DROP TABLE IF EXISTS Event;

CREATE TABLE IF NOT EXISTS Member(Name VARCHAR(20) NOT NULL, Number INT, Email VARCHAR(50) NOT NULL, SKILL INT, PRIMARY KEY(Name));

CREATE TABLE IF NOT EXISTS Commitee(MemberName VARCHAR(20) NOT NULL, Role VARCHAR(20) NOT NULL,FOREIGN KEY(MemberName) REFERENCES Member(Name),PRIMARY KEY (Role));

CREATE TABLE IF NOT EXISTS Event(HeldDate DATE NOT NULL, EventName VARCHAR(20) NOT NULL, Location VARCHAR(20) NOT NULL, Organiser VARCHAR(20) NOT NULL, Description Text, FOREIGN KEY (Organiser) REFERENCES Member(Name));
